### ISSUE TITLE
Make lm function output correlation values

### ISSUE THREAD

**Issue by KelseyChetnik** [krumsieklab/maplet#122]
In GitLab by @krumsiek on Jul 13, 2020, 16:00

For continuous outcomes only. This is just to accompany the scatter plots, no correlation-based statistical testing needed.

**Comment by krumsiek** [comment]
Seems to be the wrong approach, since `lm` does not generate correlations. We could add an optional correlation parameter to the scatterplot function instead. Otherwise, the user has to call one of the correlation functions.
