### ISSUE TITLE
Make any SE object maplet compatible

### ISSUE THREAD

**Issue by KelseyChetnik** [krumsieklab/maplet#162]
(1) write a function that converts any SE object on SE compatible one ($name column, make.names), and (2) document those requirements somewhere.

**Comment by krumsiek** [comment]
This function also needs to initialize the metadata with an initial entry, similar to a loader function.

**Comment by KelseyChetnik** [comment]
To-Do List:
- [x] check rowData and colData columns have valid R names
- [x] check "name" column present in rowData
- [x] initialize metadata with initial entry similar to loader function

**Comment by KelseyChetnik** [comment]
Questions:

1. Do the assay columns need R valid names (e.g. can't be called '1', '2', etc. which would mean sample IDs can't just be numbers)?
2. Should the function throw error if column names not valid (or change them and warn the user)?
3. Are there any additional requirements?

**Comment by KelseyChetnik** [comment]
Implemented in 88d27d22b92265af7b760bb20cf98d6508d21ac7.
